### ISSUE TITLE
Entry with orgName means status of Stock

### ISSUE THREAD

**Issue by jamescummings** [jamescummings/SRO-ODD#13]
"Ensure that all entries with an `<orgName>` have `<note type="status" subtype=“Stock”/>`
 (and please show me the ones that have that status without those conditions)"

**Comment by jamescummings** [comment]
@gbergel Finally getting to this. Can you find an example of one of these? I'm putting in a test for it but not finding any `<orgName>` elements inside an entry (only in the header)

**Comment by gbergel** [comment]
OK, this is one of those little-used elements that slipped out of both my mind, and Volume Editors. I'll review subtype="Stock" entries, apply that element and perhaps add to `<persName>` for indexing.
