### ISSUE TITLE
Delete text "Arber:" if before 'No Sum Stated'

### ISSUE THREAD

**Issue by jamescummings** [jamescummings/SRO-ODD#4]
"Please delete the text “Arber:" where it appears immediately inside a square bracket IF and ONLY IF it precedes the text "No Sum Stated"] (case-insensitive probably best, but I am pretty sure that text is consident). This note has been superceded by editors’ eyes on the Register itself, so no need to credit Arber."

**Comment by jamescummings** [comment]
@gbergel This only seems to happen in the case of:

`<note resp="#arber">Arber: no sum stated</note>`
which I could modify to 
1) `<note resp="#arber">no sum stated</note>` 
2) `<note resp="#arber">No sum stated</note>` 
3) `<note>No sum stated</note>` 
4) something else.

My assumption is that you want number 2 but don't know if the capitalization is consistent with other notes?

**Comment by gbergel** [comment]
Yes, 2. Just been through Reg. A-C and 'no' seems consistently lower-case.
