### ISSUE TITLE
Delete various <hi> inside <persName>

### ISSUE THREAD

**Issue by jamescummings** [jamescummings/SRO-ODD#5]
"Please also delete the `<hi rend=“bold">` and `<hi rend=“smallcaps">` markup on `<persName>` ONLY. This has been throughly investigated and is, again, Arber residue. Arber does use italics around ‘Senior’, ‘Junior’ etc, and we should probably suppress that as well, but keep it for now as we can maybe use that to aid normalisation. "

@gbergel: Do you mean also the `@rend` attribute ON `<persName>` or only where there is a `<hi>` element inside of `<persName>`?

**Comment by gbergel** [comment]
The latter. I think we transformed all @rend on <persName> to the appropriate @role, but we sometimes have <hi> on a part of a <persName>. We should remove all of it.

**Comment by gbergel** [comment]
Note we want to keep other <hi> markup, such as struck-through.
